# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Anypoint

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run o
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: action/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-key: |
            ${{ runner.os }}-maven-
      # Runs a single command using the runners shell
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Runs a set of commands using the runners shell
      - name: Add repo Credentials
        uses: s4u/maven-settings-action@v2.4.0
        with:
          server: |
            [{
              "id": "mule-enterprise",
              "username": "${{ secrets.mule_nexus_username }}",
              "password" : "${{ secrets.mule_nexus_password }}"
            }]
            
      - name: Build with maven
        run: mvn -B package --file pom.xml
        
      - name: Stamp artifact file with commit hash
        run : |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
          mv $artifactName1 artifactName2